---
version: "2"
services:
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    network_mode: bridge
    environment:
      - PUID=PUID:-1000
      - PGID=PGID:-1000
      - VERSION=docker
      - TZ=America_New_York
    volumes:
      - /home/op/docker-compose/radarr/config:/config
      - /mnt/disk/:/mnt/disk
    ports:
      - 7878:7878
    restart: unless-stopped
