---
version: "2"
services:
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=PUID:-1000
      - PGID=PGID:-1000
      - TZ=America_New_York
    volumes:
      - /home/op/docker-compose/jackett/config:/config
    ports:
      - 9117:9117
    restart: unless-stopped
