---
version: "2"
services:
  plex:
    image: linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=PUID:-1000
      - PGID=PGID:-1000
      - VERSION=docker
      - TZ=America_New_York
    volumes:
      - /home/op/docker-compose/plex/config:/config
      - /mnt/disk/media/movies/:/mnt/disk/
    restart: unless-stopped
