---
version: "2"
services:
  tautulli:
                image: linuxserver/tautulli
                container_name: tautulli
                environment:
                         - PUID=1000
                         - PGID=1000
                         - BASE_URL=/
                         - TZ=America/New_York
                ports:
                        - 8181:8181
                volumes:
                        - /home/op/docker-compose/tautulli/config:/config
                restart: unless-stopped
