---
version: "2"
services:
  nzbhydra2:
         image: lscr.io/linuxserver/nzbhydra2:latest
         container_name: nzbhydra2
         environment:
                    - PUID=1000
                    - PGID=1000
                    - TZ=America/New_York
         volumes:
                - /home/op/docker-compose/nzbhydra/config:/config
                - /mnt/disk/nzb:/nzb
         ports:
               - 5076:5076
         restart: unless-stopped 
